### ISSUE TITLE
bug: wrong package.json version.

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/service-core#36]
## Description

Package.json version is wrong. Needs to be updated.

**Comment by anantakumarghosh** [comment]
Closing as done.

**Comment by techoneel** [comment]
reopening this issue since the version are creating problem while clean install
![image](https://github.com/user-attachments/assets/9dd6849b-be7e-4b83-8832-0a69c8b5bf15)

**Comment by techoneel** [comment]
the identified problem resolved
![image](https://github.com/user-attachments/assets/02e59442-3667-466d-b3f2-739fd7cd7083)

**Comment by anantakumarghosh** [comment]
> reopening this issue since the version are creating problem while clean install ![image](https://private-user-images.githubusercontent.com/20424034/378877660-9dd6849b-be7e-4b83-8832-0a69c8b5bf15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTg2MzIsIm5iZiI6MTcyOTYxODMzMiwicGF0aCI6Ii8yMDQyNDAzNC8zNzg4Nzc2NjAtOWRkNjg0OWItYmU3ZS00YjgzLTg4MzItMGE2OWM4YjViZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE3MzIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzQzMDBmYjk1MTJjMjY0YWEyNGY4ODNkMTE5MGFjYmYyZTkzOWFjYjA4OTg3ZjY0MDU1ZTRjMWY3Y2Q1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IwMizQxHdEBkyvKHW9pASofgMENcnMOVaoZkxZ3xvxY)

This issue isn't directly related to the one you mentioned. It seems like there might be a misunderstanding. This issue only concerns version(**version key**) in package.json and additionally package-lock.json. The mentioned reason for reopening is supposed to be a different issue, also according to your commits, it is regarding devDependencies and peerDependencies. To avoid any confusion, I'd appreciate it if you could refrain from reopening issues unnecessarily.
