### ISSUE TITLE
enhancement: master data related changes made

### ISSUE THREAD

**Issue by techoneel** [wrappid/service-core#38]
- [ ] database helper functions
  - [x] get databases
  - [x] get tables
  - [x] get columns
- [ ] business entity helper functions
  - [ ] schema to sequelize options
- [ ] model movement to service-core
  - [x] Routes
  - [x] Pages
  - [x] Applications
  - [x] DataTableOptions
  - [x] MasterData
  - [x] StringValues
  - [x] SupportedLanguages
  - [x] CronSchemas
  - [x] SettingMeta
  - [x] ApiRequestLogs
  - [ ] ActivityLogs

**Comment by PritamIT2023** [comment]
@techoneel 
 ActivityLogs sequelize model does not exist.
