### ISSUE TITLE
enhancement: creating landing route

### ISSUE THREAD

**Issue by PritamIT2023** [wrappid/service-core#54]
**Is your feature request related to a problem? Please describe.**
create a function with below signature setupLandingRoute ( wrappidApp, options)	

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samhere17** [comment]
@jyoti1610 as discussed, please test this page and list down the issues

**Comment by jyoti1610** [comment]
**Problem :**

- [ ] Need Favicon on these website -
       1. https://stageapi.rxefy.com/
       2. https://demoapi.wrappid.dev/
  
- [ ] On the above mentioned page there has double space on right side of every pipe " | "  and single space on left side.
![image](https://github.com/wrappid/service-core/assets/88906858/bb868eb1-fb93-43f4-b7e2-df0682573ba8)

- [ ] Need to mention " yyyy " type date on footer section.
![image](https://github.com/wrappid/service-core/assets/88906858/eb116ff2-2ad3-4be4-8cc5-1f04a64d2aa9)

@PritamIT2023  and @samhere17 check it out.

**Comment by PritamIT2023** [comment]
closing as done
